### ISSUE TITLE
[serve] source code shown in devtools is out of date compared to what is being executed

### ISSUE THREAD

**Issue by davidmaxwaterman** [Polymer/tools#579] opened 2018-07-12 05:56 UTC
Ref: https://bugs.chromium.org/p/chromium/issues/detail?id=861706

When serving my app using `polymer serve`:

1. the code shown in dev tools is 'old' compared to that being executed - I can test this by evaluating variables,
2. the code shown in dev tools doesn't show the same line numbers as in the actual source code
3. the code shown often doesn't even have any html/css

If I switch to using `python -m SimpleHTTPServer 8081&`, then the above issues are gone. Noticable changes include:

1. all the files in the file navigator now have a green dot on them (also in the tabs) when they have none when using `polymer serve`,
2. the source displayed changes *immediately* I save the file in my external editor (vim), while in `polymer serve`, even reloading the app doesn't help,
3. the line numbers match 100%

$ polymer --version
1.7.7
Google Chrome | 67.0.3396.99 (Official Build) unknown (64-bit)
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
$ node --version
v8.9.4

**Comment by web-padawan** [comment] 2018-07-12 05:59
Duplicate of #389

**Closed** 2022-04-28 19:28 UTC
Labels: wontfix
