### ISSUE TITLE
polymer analyze produces broken JSON descriptor file

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [Polymer/tools#682] opened 2018-09-04 11:27 UTC
Configuration:

`polymer-cli@1.8.0`
`node@8.11.4`
`npm@6.4.1`

Problem:

`polymer analyze > analysis.json` produces broken `analysis.json` file with the following content:

```
{
  "schema_version": "1.0.0"
} 
```

The old `polymer-cli@1.6.0` produces correct JSON descriptor file.

**Comment by web-padawan** [comment] 2018-09-04 13:21
Duplicate of #361. See the explanation there.

**Closed** 2018-09-23 17:13 UTC
