### ISSUE TITLE
[cli] serving named imports resolution inconsistent for reusable components

### ISSUE THREAD

**Issue by yo3jones** [Polymer/tools#167] opened 2018-04-18 13:53 UTC
When using the reusable components url from polymer serve (ie http://127.0.0.1:8081/components/... ) the requests are inconsistent for named module imports.

Some use /components/ some use /node_modules/

This results in the error `Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry` as imports are requested twice with different urls.

This is also preventing polymer test to execute properly.

command used:
```shell
polymer serve --npm --module-resolution=node
```

**Comment by web-padawan** [comment] 2018-04-18 15:42
Looks like a duplicate of #125

**Comment by yo3jones** [comment] 2018-04-18 15:57
@web-padawan You are right, thanks.

**Comment by aomarks** [comment] 2018-04-18 21:56
Thanks for the report! Closing as dupe of #125 as noted above.

**Closed by aomarks** 2018-04-18 21:56 UTC
