### ISSUE TITLE
web-component-tester fails to install: sinonjs repository not found

### ISSUE THREAD

**Issue by abraham** [Polymer/tools#3488] opened 2020-02-10 03:24 UTC
The `https://github.com/blittle/sinon.js` repository appears to have been deleted and WCT is now not able to be installed.

```bash
$ bower install web-component-tester
npx: installed 1 in 3.301s
bower web-component-tester#*    cached https://github.com/Polymer/web-component-tester.git#6.5.0
bower web-component-tester#*  validate 6.5.0 against https://github.com/Polymer/web-component-tester.git#*
bower async#^1.5.0              cached https://github.com/caolan/async.git#1.5.2
bower async#^1.5.0            validate 1.5.2 against https://github.com/caolan/async.git#^1.5.0
bower accessibility-developer-tools#^2.10.0           cached https://github.com/GoogleChrome/accessibility-developer-tools.git#2.12.0
bower accessibility-developer-tools#^2.10.0         validate 2.12.0 against https://github.com/GoogleChrome/accessibility-developer-tools.git#^2.10.0
bower sinon-chai#^2.7.0                               cached https://github.com/domenic/sinon-chai.git#2.14.0
bower sinon-chai#^2.7.0                             validate 2.14.0 against https://github.com/domenic/sinon-chai.git#^2.7.0
bower chai#^3.2.0                                     cached https://github.com/chaijs/chai.git#3.5.0
bower chai#^3.2.0                                   validate 3.5.0 against https://github.com/chaijs/chai.git#^3.2.0
bower lodash#^3.7.0                                   cached https://github.com/lodash/lodash.git#3.10.1
bower lodash#^3.7.0                                 validate 3.10.1 against https://github.com/lodash/lodash.git#^3.7.0
bower stacky#^1.3.0                                   cached https://github.com/PolymerLabs/stacky.git#1.3.2
bower stacky#^1.3.0                                 validate 1.3.2 against https://github.com/PolymerLabs/stacky.git#^1.3.0
bower mocha#^3.1.2                                    cached https://github.com/mochajs/mocha.git#3.5.3
bower mocha#^3.1.2                                  validate 3.5.3 against https://github.com/mochajs/mocha.git#^3.1.2
bower sinonjs#^1.14.1                                 cached https://github.com/blittle/sinon.js.git#1.17.1
bower sinonjs#^1.14.1                               validate 1.17.1 against https://github.com/blittle/sinon.js.git#^1.14.1
bower test-fixture#^3.0.0                             cached https://github.com/PolymerElements/test-fixture.git#3.0.0
bower test-fixture#^3.0.0                           validate 3.0.0 against https://github.com/PolymerElements/test-fixture.git#^3.0.0
Username for 'https://github.com':        
Password for 'https://github.com': 
bower sinonjs#^1.14.1                                ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/blittle/sinon.js.git", exit code of #128 remote: Repository not found. fatal: Authentication failed for 'https://github.com/blittle/sinon.js.git/'

Additional error details:
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/blittle/sinon.js.git/'
```

**Comment by web-padawan** [comment] 2020-02-10 08:34
The original package has been removed (or marked private): https://github.com/blittle/sinon.js/

Looks like this should be fixed by using https://github.com/sinonjs/sinon/tree/v1.17

**Comment by felixzapata** [comment] 2020-02-10 09:44
another possible solution is to use the web-component-tester via node, with the flag `--npm`

**Comment by web-padawan** [comment] 2020-02-10 11:12
Thanks, WCT with `--npm` flag works because it gets [`@polymer/sinon-js`](https://github.com/Polymer/sinon.js).

The issue is specific to the Bower version. The fix for it would require another WCT release for Bower. Which means that [web-component-tester](https://github.com/Polymer/web-component-tester) repo has to be temporarily unarchived.

Another options:

1. Contact the maintainer and ask to make repo public again. @blittle could you do that?
2. Contact someone responsible of Bower maintenance to re-register package.

Registering another GitHub repo as a Bower package is no longer possible:

```sh
? Registering a package will make it installable via the registry (https://registry.bower.io), continue? Yes
bower sinonjs                 register https://github.com/Polymer/sinon.js
bower                         EUNKNOWN Unknown error: 500 - Registering bower package names is not supported anymore. You can install any bower package on github with command like "bower install jquery/jquery-dist --save"
```

**Comment by usergenic** [comment] 2020-02-11 20:43
https://github.com/Polymer/web-component-tester/pull/742 addressing this in wct repo which is used by bower registry.

**Comment by usergenic** [comment] 2020-02-11 20:51
I've updated Polymer/web-component-tester to v6.5.1 tag referencing Polymer/sinon.js in the bower.json

Please let me know if this gets you back on track

**Comment by usergenic** [comment] 2020-02-12 04:59
I'm going to close this issue.  Please reopen if you continue to have issues.  If you have locked WCT to version 6.0.0 in your bower, you'll want to open it up so it pulls latest bower'd version of 6.5.1 for this fix.

**Closed by usergenic** 2020-02-12 04:59 UTC

**Comment by abraham** [comment] 2020-02-13 04:42
Looks good to me. 👍
